export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAIL = 'UPDATE_FAIL'
export const LOGOUT = 'LOGOUT'

export const ADD_USER = 'ADD_USER'
export const GET_USERS = 'GET_USERS'
export const GET_USER = 'GET_USER'

export const SET_MESSAGE = 'SET_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

export const PROVINCE_DATA = 'PROVINCE_DATA'

export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const SET_CUSTOMER = 'SET_CUSTOMER'
export const GET_CUSTOMER = 'GET_CUSTOMER'
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER'

export const SET_METER = 'SET_METER'

export const SET_METER_READING = 'SET_METER_READING'
export const SET_METER_READING_DATA = 'SET_METER_READING_DATA'
export const UPDATE_METER_READING = 'UPDATE_METER_READING'
export const METER_READING = 'METER_READING'

export const SET_BILLING_DATA = 'SET_BILLING_DATA'
export const UPDATE_BILLING_DATA = 'UPDATE_BILLING_DATA'
export const CUSTOMER_BILLING_DATA = 'CUSTOMER_BILLING_DATA'
export const PAID_BILLING_DATA = 'PAID_BILLING_DATA'

export const ADD_NOTIFICATIONS = 'ADD_NOTIFICATIONS'
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const PUT_NOTIFICATIONS = 'PUT_NOTIFICATIONS'